import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import os from "node:os";
import {
  generateModel,
  generateEnum,
  generateRegistry,
  parseSchema,
  cleanOldGeneratedFiles,
} from "../src/parser";

test("generateEnum generates enum type and values array", () => {
  const code = generateEnum({
    name: "Role",
    values: ["ADMIN", "USER"],
  });

  assert.match(code, /export enum Role/);
  assert.match(code, /ADMIN = "ADMIN"/);
  assert.match(code, /USER = "USER"/);
  assert.match(code, /export const RoleValues = \["ADMIN", "USER"\] as const;/);
});

test("generateModel generates class extending Base with static override getter", () => {
  const model = {
    name: "User",
    fields: [
      {
        name: "id",
        type: "String",
        isArray: false,
        required: true,
        isRelation: false,
        relationField: null,
        attributes: { id: null },
      },
      {
        name: "role",
        type: "Role",
        isArray: false,
        required: true,
        isRelation: false,
        relationField: null,
        attributes: {},
      },
    ],
  };

  const enums = [{ name: "Role", values: ["ADMIN", "USER"] }];

  const code = generateModel(model, enums);

  assert.match(code, /export class User extends Base/);
  assert.match(code, /static override get schema\(\): SchemaDefinition/);
  assert.match(code, /import \{ Role, RoleValues \} from '\.\/Role';/);
  assert.match(code, /enum: RoleValues/);
});

test("generateRegistry generates exports and registry map", () => {
  const models = [{ name: "User", fields: [] }];
  const enums = [{ name: "Role", values: ["ADMIN"] }];

  const code = generateRegistry(models, enums);

  assert.match(code, /export \{ Role \} from '\.\/Role';/);
  assert.match(code, /export \{ User \} from '\.\/User';/);
  assert.match(code, /export const registry = \{/);
  assert.match(code, /User: _User,/);
});

test("parseSchema correctly extracts models and enums from Prisma schema", () => {
  const schemaStr = `
    enum Status {
      ACTIVE
      INACTIVE
    }

    model Post {
      id        String   @id @default(uuid())
      title     String
      status    Status   @default(ACTIVE)
      createdAt DateTime @default(now()) @updatedAt
    }
  `;

  const { models, enums } = parseSchema(schemaStr);

  assert.equal(enums.length, 1);
  assert.equal(enums[0].name, "Status");
  assert.deepEqual(enums[0].values, ["ACTIVE", "INACTIVE"]);

  assert.equal(models.length, 1);
  assert.equal(models[0].name, "Post");
  assert.equal(models[0].fields.length, 4);
  assert.equal(models[0].fields[0].name, "id");
  assert.equal(models[0].fields[0].type, "String");
});

test("cleanOldGeneratedFiles removes stale auto-generated files", () => {
  const tempDir = fs.mkdtempSync(path.join(os.tmpdir(), "modelcore-test-"));
  const staleFile = path.join(tempDir, "StaleModel.ts");
  const userFile = path.join(tempDir, "UserCustom.ts");

  fs.writeFileSync(
    staleFile,
    "// Auto-generated by prisma-modelcore\nexport class Stale {}"
  );
  fs.writeFileSync(userFile, "// Custom user code\nexport class Custom {}");

  cleanOldGeneratedFiles(tempDir);

  assert.equal(fs.existsSync(staleFile), false);
  assert.equal(fs.existsSync(userFile), true);

  fs.rmSync(tempDir, { recursive: true, force: true });
});
